include cc71x_tee_ree/cc71x_tee_ree.mk

INCDIRS_FLAVOUR += $(HOST_PROJ_ROOT)/../shared/include/crypto_api
INCDIRS_FLAVOUR += $(HOST_PROJ_ROOT)/../shared/include/crypto_api/$(PROJ_PRD)

DEPLIBS_EXTRA += cc_713tee
